// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJk68ye3V1pIjk83YlYd-VqOU5I_Xb7Y',
    appId: '1:407839163935:web:8a52996cd27a8f04f3772a',
    messagingSenderId: '407839163935',
    projectId: 'network-attendance',
    authDomain: 'network-attendance.firebaseapp.com',
    storageBucket: 'network-attendance.firebasestorage.app',
    measurementId: 'G-SQN8QVT5Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDicLifZkAFsXUDeYlEhL9DGOoKfy-shBA',
    appId: '1:407839163935:android:6afdf4607b3bcbd0f3772a',
    messagingSenderId: '407839163935',
    projectId: 'network-attendance',
    storageBucket: 'network-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUK4x4GEI9pVDSUSaDQ32pV2O5n70Cf0',
    appId: '1:407839163935:ios:cf72cbb7387593c4f3772a',
    messagingSenderId: '407839163935',
    projectId: 'network-attendance',
    storageBucket: 'network-attendance.firebasestorage.app',
    iosBundleId: 'com.example.fileSender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsUK4x4GEI9pVDSUSaDQ32pV2O5n70Cf0',
    appId: '1:407839163935:ios:cf72cbb7387593c4f3772a',
    messagingSenderId: '407839163935',
    projectId: 'network-attendance',
    storageBucket: 'network-attendance.firebasestorage.app',
    iosBundleId: 'com.example.fileSender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPJk68ye3V1pIjk83YlYd-VqOU5I_Xb7Y',
    appId: '1:407839163935:web:77f3020966098e0df3772a',
    messagingSenderId: '407839163935',
    projectId: 'network-attendance',
    authDomain: 'network-attendance.firebaseapp.com',
    storageBucket: 'network-attendance.firebasestorage.app',
    measurementId: 'G-LSSXGFLWDR',
  );
}
